iota_auth/urls.py
from django.urls import path, include

from .views import (
	LoginView, 
	SignupView,
	LogoutView,
	AuthenticatedView,
	)

app_name = 'iota_auth'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', AuthenticatedView.as_view(), name='authenticated'),
]

iota_auth/templates/iota_auth/authenticated.html
{% extends 'iota_auth/base.html' %}
{% block layout_class %}mdl-layout--no-desktop-drawer-button{% endblock %}
{% block header_class %}{% endblock %}
{% block particles_bg %}<div id="particles-js"></div>{% endblock %}
{% block body %}
	<div class="mdl-grid mdl-grid--fill">
		<div class="mdl-cell mdl-cell--middle mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--4-col-phone">
			<div class="mdl-card mdl-shadow--4dp">
				<div class="mdl-card__title">
					<h2 class="mdl-card__title-text">Whoo {{ request.user.first_name }}, you're connected to the Tangle</h2>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

iota_auth/templates/iota_auth/base.html
{% load static %}
<!doctype html>
<html lang="en">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta charset="utf-8">
		<title>Django Iota Auth</title>
		<meta name="description" content="A test implementation of Django and IOTA">
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		<link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
		<script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
		<link rel="stylesheet" href="{% static 'iota_auth/css/iota_auth.css' %}">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	</head>
	<body>
		{% block particles_bg %}{% endblock %}
		<div class="mdl-layout mdl-js-layout {% block layout_class %}{% endblock %}">
			<header class="mdl-layout__header {% block header_class %}{% endblock %}">
			{% include 'header.html' %}
		</header>
			{% include 'drawer.html' %}
			<main class="mdl-layout__content mdl-content__width {% block main_class%}{% endblock %}">
				{% block body %}
				{% endblock %}
			</main>
		</div>
		<script type="text/javascript" src="{% static 'iota_auth/js/particles.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'iota_auth/js/app.js' %}"></script>
		{% block scripts %}{% endblock %}
	</body>
</html>

iota_auth/templates/iota_auth/drawer.html
<div class="mdl-layout__drawer">
	<span class="mdl-layout-title">Django-Iota_auth</span>
	<nav class="mdl-navigation">
		{% if not user.is_authenticated %}
			<a class="mdl-navigation__link" href="{% url 'iota_auth:login' %}">Login</a>
			<a class="mdl-navigation__link" href="{% url 'iota_auth:signup' %}">Signup</a>
		{% else %}
			<a class="mdl-navigation__link"">{{ request.user.email }}</a>
			<a class="mdl-navigation__link" href="{% url 'iota_account:account' request.user.pk %}">Account</a>
			<a class="mdl-navigation__link" href="{% url 'iota_auth:logout' %}">Logout</a>
		{% endif %}
	</nav>
</div>

iota_auth/templates/iota_auth/header.html
<div class="mdl-layout__header-row">
	<span class="mdl-layout-title">Django-Iota-Auth</span>
	<div class="mdl-layout-spacer"></div>
	<nav class="mdl-navigation">
		{% if not user.is_authenticated %}
			<a class="mdl-navigation__link" href="{% url 'iota_auth:login' %}">Login</a>
			<a class="mdl-navigation__link" href="{% url 'iota_auth:signup' %}">Signup</a>
		{% else %}
			<a class="mdl-navigation__link"">{{ request.user.email }}</a>
		{% endif %}
	</nav>
	<!-- Right aligned menu below button -->
	<button id="demo-menu-lower-right"
	class="mdl-button mdl-js-button mdl-button--icon">
	<i class="material-icons">more_vert</i>
	</button>
	<ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
		for="demo-menu-lower-right">
		<a class="mdl-menu__item" href="{% url 'iota_account:account' request.user.pk %}">Account</a>
		<a class="mdl-menu__item" href="{% url 'iota_auth:logout' %}">Logout</a>
	</ul>
</div>

iota_auth/templates/iota_auth/login.html
{% extends 'iota_auth/base.html' %}
{% block body %}
	<div class="mdl-grid mdl-grid--fill">
		<div class="mdl-cell mdl-cell--middle mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--4-col-phone">
			<div class="mdl-card mdl-shadow--4dp">
				<div class="mdl-card__title">
					<h2 class="mdl-card__title-text">Django-Iota-Auth</h2>
				</div>
				<div class="mdl-card__supporting-text">
					<form action="/login/" method="POST">
						{% csrf_token %}
						{{ form.non_field_errors }}
						{{ field.errors }}
						<div>
						{{ form.email.label }}
						{{ form.email }}
					</div>
						<div>
						{{ form.password.label }}
						{{ form.password }}
					</div>
					<div>
						{{ form.remember.label }}
						{{ form.remember }}
					</div>
					</div>
					<div class="mdl-card__actions mdl-card--border">
						<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">Login</button>
					</form>
					Don't have a seed? <a href="{% url 'iota_auth:signup' %}">Signup</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

iota_auth/templates/iota_auth/logout.html
{% extends 'iota_auth/base.html' %}
{% block layout_class %}mdl-layout__header--transparent mdl-layout--no-desktop-drawer-button{% endblock %}
{% block header_class %}mdl-layout__header--transparent{% endblock %}
{% block particles_bg %}<div id="particles-js"></div>{% endblock %}
{% block body %}
	<div class="mdl-grid mdl-grid--fill">
		<div class="mdl-cell mdl-cell--middle mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--4-col-phone">
			<div class="mdl-card mdl-shadow--4dp">
				<div class="mdl-card__title">
					<h2 class="mdl-card__title-text">Django-Iota-Auth</h2>
				</div>
				<div class="mdl-card__supporting-text">
					<form action="." method="POST">
						{% csrf_token %}
						<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">Logout</button>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

iota_auth/templates/iota_auth/signup.html
{% extends 'iota_auth/base.html' %}
{% block layout_class %}mdl-layout__header--transparent mdl-layout--no-desktop-drawer-button{% endblock %}
{% block header_class %}mdl-layout__header--transparent{% endblock %}
{% block particles_bg %}<div id="particles-js"></div>{% endblock %}
{% load static %}
{% block body %}
	<div class="mdl-grid mdl-grid--fill">
		<div class="mdl-cell mdl-cell--middle mdl-cell--4-col mdl-cell--4-col-tablet mdl-cell--4-col-phone">
			<div class="mdl-card mdl-shadow--4dp">
				<div class="mdl-card__title">
					<h2 class="mdl-card__title-text">Django-Iota-Auth</h2>
				</div>
				<div class="mdl-card__supporting-text">
					<div>
						Already have an account? <a href="{% url 'iota_auth:login' %}">Login</a>
					</div>
					<form method="POST">
						{% csrf_token %}
						{{ form.non_field_errors }}
						{{ field.errors }}
						<div>
						{{ form.email.label }}
						{{ form.email }}
						</div>
						<div>
						{{ form.first_name.label }}
						{{ form.first_name }}
						</div>
						<div>
						{{ form.last_name.label }}
						{{ form.last_name }}
						</div>
						<div>If you already have an Iota seed, please enter below. If not, you need to enter a seed of at least 81 alphabet characters, and the letter 9. You can use our seed generation service below. Save this seed as it is like your username and password to access your account. If you lose it, you will lose access to your account and your Iota.</div>
						<div>
						{{ form.seed.label }}
						{{ form.seed }}
						</div>
						<a id="generate_seed_button" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent">Generate a seed</a>
						<div>Your seed is:</div>
						<div id="seed_generated"></div>
					</div>
					<div class="mdl-card__actions mdl-card--border">
						<button class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">Signup</button>
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="{% static 'iota_auth/js/iota_auth.js' %}"></script>
{% endblock %}

iota_auth/templates/iota_auth/user_update_form.html
{% extends 'iota_account/account_subnav.html' %}
{% block account_body %}
	<div class="mdl-cell mdl-cell--middle mdl-cell--9-col mdl-cell--6-col-tablet mdl-cell--4-col-phone">
		<div class="mdl-card mdl-card--fill mdl-shadow--4dp">
			<div class="mdl-card__supporting-text">
				{{ form.as_p }}
				<input class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect" type="submit" value="Update" />
			</div>
		</div>
	</div>
{% endblock %}